# Revised environment.yml from Chris Kirney, emailed 2022 11 08

# based on install commands:
# conda create --prefix ./envs python=3.9
# conda install -c conda-forge boto3 conda dash dash-core-components dash-html-components dash-renderer dash-table docker-py icecream openpyxl pandas pip plotly psycopg2 pyyaml scikit-learn scikit-optimize sqlalchemy
# pip install pymoo dash-bootstrap-components

#packages and depencies locked versions below.
# conda env create --prefix ./env --file environment.yml
#List lock versions
# conda env export
# Update environment based on this file.
# conda env update --prefix ./env --file environment.yml  --prune
name: btap_batch
channels:
  - conda-forge
  - defaults
dependencies:
 - python=3.9.7
 - dash
 - dash-core-components
 - dash-html-components
 - dash-renderer
 - dash-table
 - docker-py
 - icecream
 - openpyxl
 - pandas
 - plotly
 - psycopg2
 - pyyaml
 - scikit-learn
 - scikit-optimize
 - sqlalchemy
 - boto3
 - tqdm
 - pip
 - pip:
   - openstudio==3.2.1
   - pymoo==0.5.0
   - autograd
   - cma
   - numpy-financial
   - boto3