name: btap_batch
channels:
  - defaults
  - conda-forge
dependencies:
  - sqlalchemy
  - pandas
  - dash
  - psycopg2
  - conda
  - scikit-learn
  - pip
  - pyyaml
  - python=3.8
  - docker-py
  - openpyxl
  - boto3
  - dash-bootstrap-components
  - pip:
      - pymoo
