name: btap_batch
channels:
  - defaults
dependencies:
  - conda
  - python=3.8
  - scikit-learn
  - docker-py
  - pyyaml
  - boto3
  - pandas
  - sqlalchemy
  - psycopg2
  - openpyxl
  - pip
  - pip:
    - pymoo
