# based on install commands:
# conda create --prefix ./envs python=3.9
# conda install -c conda-forge boto3 conda dash dash-core-components dash-html-components dash-renderer dash-table docker-py icecream openpyxl pandas pip plotly psycopg2 pyyaml scikit-learn scikit-optimize sqlalchemy
# pip install pymoo dash-bootstrap-components

#packages and depencies locked versions below.
# conda env create --prefix ./env --file environment.yml
#List lock versions
# conda env export
# Update environment based on this file.
# conda env update --prefix ./env --file environment.yml  --prune
name: btap_batch
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs
  - asn1crypto
  - asttokens
  - blas
  - boto3
  - botocore
  - bottleneck
  - brotli-python
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - conda
  - conda-package-handling
  - cryptography
  - cycler
  - dash-renderer
  - dataclasses
  - docker-py
  - docker-pycreds
  - et_xmlfile
  - executing
  - flask
  - flask-compress
  - freetype
  - future
  - greenlet
  - icecream
  - idna
  - intel-openmp
  - itsdangerous
  - jbig
  - jdcal
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - liblapack
  - libpng
  - libpq
  - libtiff
  - lz4-c
  - markupsafe
  - matplotlib-base
  - mkl
  - mkl-service
  - numexpr
  - numpy
  - olefile
  - openjpeg
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - plotly
  - psycopg2
  - pyaml
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python=3.9.7
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - pyyaml
  - requests
  - ruamel_yaml
  - s3transfer
  - scikit-learn
  - scikit-optimize
  - scipy
  - setuptools
  - six
  - sqlalchemy
  - sqlite
  - tbb
  - tenacity
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - tzdata
  - urllib3
  - websocket-client
  - werkzeug
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - autograd==1.3
    - cma==2.7.0
    - dash==2.0.0
    - dash-bootstrap-components==1.0.0b3
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - numpy-financial==1.0.0
    - openstudio==3.2.1
    - pymoo==0.5.0
